<template>
    <v-container class="keyboard">
      <ul v-for="row in keyboard" :key="row" class="row row-1">
        <li v-for="item in row"
            :key="item"
            :class="item.finger"
            :id="item.letter"
            :style="{width: item.sizing}"
        >{{ item.letter }}</li>
      </ul>
    </v-container>
</template>

<script>


export default {
  name: "KeyboardHero",
  data () {
    return {
       keyboard: {
        row: [
            {
              letter: 'TAB',
              finger: 'pinky',
              sizing: '5em'
            },
          {
               letter: 'Q',
               finger: 'pinky',
               sizing: '3em'
             },
             {
               letter: 'W',
               finger: 'ring',
               sizing: '3em'
             },
             {
               letter: 'E',
               finger: 'middle',
               sizing: '3em'
             },
            {
              letter: 'R',
              finger: 'pointer',
              sizing: '3em'
            },
            {
              letter: 'T',
              finger: 'pointer',
              sizing: '3em'
            },
            {
              letter: 'Y',
              finger: 'pointer',
              sizing: '3em'
            },
            {
              letter: 'U',
              finger: 'pointer',
              sizing: '3em'
            },
            {
              letter: 'I',
              finger: 'middle',
              sizing: '3em'
            },
            {
              letter: 'O',
              finger: 'ring',
              sizing: '3em'
            },
            {
              letter: 'P',
              finger: 'pinky',
              sizing: '3em'
            },
            {
              letter: '[',
              finger: 'pinky',
              sizing: '3em'
            },
            {
              letter: ']',
              finger: 'pinky',
              sizing: '3em'
            },
            {
              letter: '\\',
              finger: 'pinky',
              sizing: '3em'
            },
           ]
       }
    }
  }
}
</script>


<style scoped>
/* GENERIC KEYBOARD STYLINGS */
.keyboard {
  display: flex;
  flex-direction: column;
  align-content: center;
  align-items: center;
}

.row {
  list-style: none;
  flex-wrap: nowrap;
  display: flex;
}

li {
  /*height: 3em;*/
  width: 3em;
  color: rgba(0, 0, 0, 0.7);
  border-radius: 0.4em;
  line-height: 3em;
  letter-spacing: 0.1em;
  margin: 0.4em;
  transition: 0.3s;
  text-align: center;
  font-size: 1em;
}

/* SPECIAL KEYS STYLINGS */
#tab {
  width: 5em;
}

#caps {
  width: 6em;
}

#left-shit {
  width: 8em;
}

#enter {
  width: 6em;
}

#right-shift {
  width: 8em;
}

#back {
  width: 5em;
}

/* HAND POSITION COLOURING */
.pinky {
  background-color: coral;
  border: 2px solid coral;
}

.pinky.selected {
  color: coral;
}

.ring {
  background-color: darkorange;
  border: 2px solid darkorange;
}

.ring.selected {
  color: darkorange;
}

.middle {
  background-color: gold;
  border: 2px solid gold;
}

.middle.selected {
  color: gold;
}

.pointer {
  background-color: khaki;
  border: 2px solid khaki;
}

.pointer.selected {
  color: khaki;
}

.selected {
  background-color: transparent;
  -webkit-animation: vibrate-1 0.5s linear infinite both;
  animation: vibrate-1 0.5s linear infinite both;
}

/* ANIMATIONS */
/* ----------------------------------------------
 * Generated by Animista on 2021-9-8 22:6:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation vibrate-1
 * ----------------------------------------
 */
@-webkit-keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
    transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
}
@keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
    transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
}

</style>