<template>
    <v-container class="keyboard">
      <ul class="row row-1">
        <li v-for="item in TopRow" :key="item.letter"
            :class="item.finger"
            :id="item.letter"
            :style="{width: item.sizing}"
        >{{ item.letter }} </li>
      </ul>
      <ul class="row row-2">
        <li v-for="item in UpperRow" :key="item.letter"
            :class="item.finger"
            :id="item.letter"
            :style="{width: item.sizing}"
        >{{ item.letter }} </li>
      </ul>
      <ul class="row row-3">
        <li v-for="item in LowerRow" :key="item.letter"
            :class="item.finger"
            :id="item.letter"
            :style="{width: item.sizing}"
        >{{ item.letter }} </li>
      </ul>
      <ul class="row row-4">
        <li v-for="item in BottomRow" :key="item.letter"
            :class="item.finger"
            :id="item.letter"
            :style="{width: item.sizing}"
        >{{ item.letter }} </li>
      </ul>
    </v-container>
</template>

<script>
import keyboardContent from '../static/keyboardContent.json'

export default {
  name: "KeyboardHero",
  data () {
    return {
      keyboard: keyboardContent
    }
  },
  created() {
    console.log(this.keyboard)
  },
  computed: {
    TopRow () {
      return this.keyboard.filter(key => key.row === 1).sort((x, y) => x.rowIndex - y.rowIndex)
    },
    UpperRow () {
      return this.keyboard.filter(key => key.row === 2).sort((x, y) => x.rowIndex - y.rowIndex)
    },
    LowerRow () {
      return this.keyboard.filter(key => key.row === 3).sort((x, y) => x.rowIndex - y.rowIndex)
    },
    BottomRow () {
      return this.keyboard.filter(key => key.row === 4).sort((x, y) => x.rowIndex - y.rowIndex)
    },
  }
}
</script>


<style scoped>
/* GENERIC KEYBOARD STYLINGS */
.keyboard {
  display: flex;
  flex-direction: column;
  align-content: center;
  align-items: center;
}

.row {
  list-style: none;
  flex-wrap: nowrap;
  display: flex;
}

li {
  /*height: 3em;*/
  width: 3em;
  color: rgba(0, 0, 0, 0.7);
  border-radius: 0.4em;
  line-height: 3em;
  letter-spacing: 0.1em;
  margin: 0.4em;
  transition: 0.3s;
  text-align: center;
  font-size: 1em;
}

/* SPECIAL KEYS STYLINGS */
#tab {
  width: 5em;
}

#caps {
  width: 6em;
}

#left-shit {
  width: 8em;
}

#enter {
  width: 6em;
}

#right-shift {
  width: 8em;
}

#back {
  width: 5em;
}

/* HAND POSITION COLOURING */
.pinky {
  background-color: coral;
  border: 2px solid coral;
}

.pinky.selected {
  color: coral;
}

.ring {
  background-color: darkorange;
  border: 2px solid darkorange;
}

.ring.selected {
  color: darkorange;
}

.middle {
  background-color: gold;
  border: 2px solid gold;
}

.middle.selected {
  color: gold;
}

.pointer {
  background-color: khaki;
  border: 2px solid khaki;
}

.pointer.selected {
  color: khaki;
}

.selected {
  background-color: transparent;
  -webkit-animation: vibrate-1 0.5s linear infinite both;
  animation: vibrate-1 0.5s linear infinite both;
}

/* ANIMATIONS */
/* ----------------------------------------------
 * Generated by Animista on 2021-9-8 22:6:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation vibrate-1
 * ----------------------------------------
 */
@-webkit-keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
    transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
}
@keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
    transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
}

</style>