<template>
  <ul class="row">
    <li v-for="item in row" :key="item.letter"
        :id="item.letter"
        :class="[currentKey === item.letter ? 'selected' : '', item.finger]"
        :style="{width: item.sizing}"
    >{{ item.letter }}</li>
  </ul>
</template>

<script>
export default {
  name: "KeyboardRow",
  props: {
    row: {
      type: Array,
      required: true
    },
    currentKey: {
      type: String,
      required: true
    }
  }
}
</script>

<style scoped>
/* GENERIC KEYBOARD STYLINGS */
.row {
  list-style: none;
  flex-wrap: nowrap;
  display: flex;
}

li {
  /*height: 3em;*/
  width: 3em;
  color: rgba(0, 0, 0, 0.7);
  border-radius: 0.4em;
  line-height: 3em;
  letter-spacing: 0.1em;
  margin: 0.4em;
  transition: 0.3s;
  text-align: center;
  font-size: 1em;
}

/* HAND POSITION COLOURING */
.pinky {
  background-color: coral;
  border: 2px solid coral;
}

.pinky.selected {
  color: coral;
}

.ring {
  background-color: darkorange;
  border: 2px solid darkorange;
}

.ring.selected {
  color: darkorange;
}

.middle {
  background-color: gold;
  border: 2px solid gold;
}

.middle.selected {
  color: gold;
}

.pointer {
  background-color: khaki;
  border: 2px solid khaki;
}

.pointer.selected {
  color: khaki;
}

.selected {
  background-color: transparent;
  -webkit-animation: vibrate-1 0.5s linear infinite both;
  animation: vibrate-1 0.5s linear infinite both;
}


/* ANIMATIONS */
/* ----------------------------------------------
 * Generated by Animista on 2021-9-8 22:6:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation vibrate-1
 * ----------------------------------------
 */
@-webkit-keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
    transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
}
@keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
    transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
}


</style>